# Generated by Django 5.1 on 2025-10-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='user',
            new_name='developer',
        ),
    ]
