# Generated by Django 5.2.5 on 2025-09-21 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workspace_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 10, 42, 14, 722640, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
