# Generated by Django 5.2.5 on 2025-09-21 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_apikey_expires_at_alter_apikey_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='accounts.workspace'),
        ),
    ]
