# Generated by Django 5.2.5 on 2025-09-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workspace_apikey'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assignments', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='course',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CourseMaterials', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='progress',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Progress', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='submission',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Submissions', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
